CREATE TABLE CITIES(NAME TEXT, CITY_GROUP INTEGER);

INSERT INTO CITIES VALUES("HELSINKI", 1);

INSERT INTO CITIES VALUES("ESPOO", 2);
INSERT INTO CITIES VALUES("KAUNIAINEN", 2);
INSERT INTO CITIES VALUES("VANTAA", 2);

INSERT INTO CITIES VALUES("HYVINKÄÄ", 3);
INSERT INTO CITIES VALUES("HÄMEENLINNA", 3);
INSERT INTO CITIES VALUES("JOENSUU", 3);
INSERT INTO CITIES VALUES("JYVÄSKYLÄ", 3);
INSERT INTO CITIES VALUES("JÄRVENPÄÄ", 3);
INSERT INTO CITIES VALUES("KAJAANI", 3);
INSERT INTO CITIES VALUES("KERAVA", 3);
INSERT INTO CITIES VALUES("KIRKKONUMMI", 3);
INSERT INTO CITIES VALUES("KOUVOLA", 3);
INSERT INTO CITIES VALUES("KUOPIO", 3);
INSERT INTO CITIES VALUES("LAHTI", 3);
INSERT INTO CITIES VALUES("LAPPEENRANTA", 3);
INSERT INTO CITIES VALUES("LOHJA", 3);
INSERT INTO CITIES VALUES("MIKKELI", 3);
INSERT INTO CITIES VALUES("NOKIA", 3);
INSERT INTO CITIES VALUES("NURMIJÄRVI", 3);
INSERT INTO CITIES VALUES("OULU", 3);
INSERT INTO CITIES VALUES("PORI", 3);
INSERT INTO CITIES VALUES("PORVOO", 3);
INSERT INTO CITIES VALUES("RAISIO", 3);
INSERT INTO CITIES VALUES("RIIHIMÄKI", 3);
INSERT INTO CITIES VALUES("ROVANIEMI", 3);
INSERT INTO CITIES VALUES("SEINÄJOKI", 3);
INSERT INTO CITIES VALUES("SIPOO", 3);
INSERT INTO CITIES VALUES("SIUNTIO", 3);
INSERT INTO CITIES VALUES("TAMPERE", 3);
INSERT INTO CITIES VALUES("TURKU", 3);
INSERT INTO CITIES VALUES("TUUSULA", 3);
INSERT INTO CITIES VALUES("VAASA", 3);
INSERT INTO CITIES VALUES("VIHTI", 3);
